### ISSUE TITLE
Codec plays real funny if you try middling bitrates like 33075

### ISSUE THREAD

**Issue by pootinanny** [dbry/adpcm-xq#20] opened 2024-09-10 10:03 UTC
While it throws no errors, if you try to convert a 16-bit wav that's got a 33075 bitrate you end up with a jumbled puzzle piece as it seems to only be able to grab some data from each chunk.

**Comment by dbry** [comment] 2024-09-10 14:59
Sorry you're having trouble! There is a weird situation where sample rates between 33,000 Hz and 43,999 Hz will end up with a "halfway" block size (768 bytes for mono, 1536 bytes for stereo).

This shouldn't actually be a problem (`FFmpeg` plays them fine) however it might be an issue for what you're playing them on (you don't say).

You should be able to fix this by adding the -b option to the command-line to force a specific block size. Adding `-b10` will force 1024 bytes and adding `-b11` will force 2048 bytes.

Let me know if that fixes it. Otherwise we can look into something else.

**Comment by pootinanny** [comment] 2024-09-11 01:15
interesting, ill give this a shot.

Is there any way to force conversion to dump bytes from the last block to ensure additional silence is not appended when the final block exceeds the included data?

**Comment by dbry** [comment] 2024-09-12 02:10
I've pushed a fix for your first issue that forces power-of-two block sizes for all sample rates. Thanks for reporting this!

The last block _is_ truncated according to the number of remaining samples. However, the IMA-ADPCM spec requires blocks be aligned on 4-byte boundaries, so that means a _maximum_ of 15 mono samples (or 7 stereo samples) could still remain. Is that what you are referring to?

Also, there is a FACT chunk that is required for all non-PCM WAV files that indicates the _exact_ number of valid samples in the file which, among other things, allows seamless looping. Players should use that to stop decoding when they get to the end, but many decoders ignore or misinterpret it.

**Comment by pootinanny** [comment] 2024-09-12 02:21
I'm not 100% sure on the second.

I use FLStudio to create my initial exports, these are exported as 44khz
16-bit integer, most of these when converted with ADPCM-XQ will have the
exact right length when brought into other tools, however occasionally I'll
see some bleed at the end that is unexpected.

There is certainly a chance that ive misselected my export points before
hand, but its too common to be user error, and not common enough to be a
universal tool error.

**Comment by dbry** [comment] 2024-09-12 20:46
Haha, I know how that goes!

Anyway, if you see something consistent that can be reproduced, let me know...

**Comment by dbry** [comment] 2024-09-17 21:04
Initial issue seems to be fixed. Thanks!

**Closed as completed by dbry** 2024-09-17 21:04 UTC
